### ISSUE TITLE
Change wheels in/out to toggle

### ISSUE THREAD

**Issue by billknopfjr** [Team2338/FRC2023#32]
Moving the wheels in and out currently uses 2 buttons.
Change this so it is a toggle when pressing in the right driver joystick

**Comment by tharunS123** [comment]
Added in ts-arm-2.0 branch

**Comment by billknopfjr** [comment]
remove in OI ...
dY.onTrue(new WheelsIn());
dB.onTrue(new WheelsOut());

**Comment by billknopfjr** [comment]
I think in ToggleWheelsInAndOut, IsFinished needs to return true
